USE GD2C2019;

DROP table [HPBC].[Funcion_Por_Rol]
DROP table [HPBC].[Funcion]
DROP table [HPBC].[Rol_Por_Usuario]
DROP table [HPBC].[Rol]
DROP table [HPBC].[Administrativo]
DROP table [HPBC].[Detalle_Fact]
DROP table [HPBC].[Factura]
DROP table [HPBC].[Cupon]
DROP table [HPBC].[Compra]
DROP table [HPBC].[Credito]
DROP table [HPBC].[Oferta]
DROP table [HPBC].[Tipo_Pago]
DROP table [HPBC].[Cliente]
DROP table [HPBC].[Proveedor]
DROP table [HPBC].[Rubro]
DROP table [HPBC].[Usuario]
DROP FUNCTION [HPBC].[Hash_Contraseña]

